apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: starter-spring-boot-cloud-k8s
build:
  artifacts:
    - image: tbo/admin
      jib:
        project: admin-service
    - image: tbo/gateway
      jib:
        project: gateway-service
    - image: tbo/department
      jib:
        project: department-service
        args:
          - -DskipTests
    - image: tbo/employee
      jib:
        project: employee-service
        args:
          - -DskipTests
    - image: tbo/organization
      jib:
        project: organization-service
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/*
    - admin-service/k8s/*.yaml
    - department-service/k8s/*.yaml
    - employee-service/k8s/*.yaml
    - organization-service/k8s/*.yaml
    - gateway-service/k8s/*.yaml
deploy:
  kubectl: {}
