apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: gateway
  type: ClusterIP